# .goreleaser.yaml
version: 2

project_name: bgp-stream

before:
  hooks:
    - go mod tidy

builds:
  - id: bgp-viewer-amd64
    main: ./cmd/bgp-viewer/main.go
    binary: bgp-viewer
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=ebitengine

  - id: bgp-viewer-arm64
    main: ./cmd/bgp-viewer/main.go
    binary: bgp-viewer
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=ebitengine

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - audio/**/*
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
