// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/v1.proto

package bgpproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsBucket struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Announcements       int32                  `protobuf:"varint,1,opt,name=announcements,proto3" json:"announcements,omitempty"`
	Withdrawals         int32                  `protobuf:"varint,2,opt,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	TotalMessages       int32                  `protobuf:"varint,3,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	PathChanges         int32                  `protobuf:"varint,4,opt,name=path_changes,json=pathChanges,proto3" json:"path_changes,omitempty"`
	CommunityChanges    int32                  `protobuf:"varint,5,opt,name=community_changes,json=communityChanges,proto3" json:"community_changes,omitempty"`
	NextHopChanges      int32                  `protobuf:"varint,6,opt,name=next_hop_changes,json=nextHopChanges,proto3" json:"next_hop_changes,omitempty"`
	AggregatorChanges   int32                  `protobuf:"varint,7,opt,name=aggregator_changes,json=aggregatorChanges,proto3" json:"aggregator_changes,omitempty"`
	PathLengthIncreases int32                  `protobuf:"varint,8,opt,name=path_length_increases,json=pathLengthIncreases,proto3" json:"path_length_increases,omitempty"`
	PathLengthDecreases int32                  `protobuf:"varint,9,opt,name=path_length_decreases,json=pathLengthDecreases,proto3" json:"path_length_decreases,omitempty"`
	MedChanges          int32                  `protobuf:"varint,10,opt,name=med_changes,json=medChanges,proto3" json:"med_changes,omitempty"`
	LocalPrefChanges    int32                  `protobuf:"varint,11,opt,name=local_pref_changes,json=localPrefChanges,proto3" json:"local_pref_changes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatsBucket) Reset() {
	*x = StatsBucket{}
	mi := &file_v1_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsBucket) ProtoMessage() {}

func (x *StatsBucket) ProtoReflect() protoreflect.Message {
	mi := &file_v1_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsBucket.ProtoReflect.Descriptor instead.
func (*StatsBucket) Descriptor() ([]byte, []int) {
	return file_v1_v1_proto_rawDescGZIP(), []int{0}
}

func (x *StatsBucket) GetAnnouncements() int32 {
	if x != nil {
		return x.Announcements
	}
	return 0
}

func (x *StatsBucket) GetWithdrawals() int32 {
	if x != nil {
		return x.Withdrawals
	}
	return 0
}

func (x *StatsBucket) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *StatsBucket) GetPathChanges() int32 {
	if x != nil {
		return x.PathChanges
	}
	return 0
}

func (x *StatsBucket) GetCommunityChanges() int32 {
	if x != nil {
		return x.CommunityChanges
	}
	return 0
}

func (x *StatsBucket) GetNextHopChanges() int32 {
	if x != nil {
		return x.NextHopChanges
	}
	return 0
}

func (x *StatsBucket) GetAggregatorChanges() int32 {
	if x != nil {
		return x.AggregatorChanges
	}
	return 0
}

func (x *StatsBucket) GetPathLengthIncreases() int32 {
	if x != nil {
		return x.PathLengthIncreases
	}
	return 0
}

func (x *StatsBucket) GetPathLengthDecreases() int32 {
	if x != nil {
		return x.PathLengthDecreases
	}
	return 0
}

func (x *StatsBucket) GetMedChanges() int32 {
	if x != nil {
		return x.MedChanges
	}
	return 0
}

func (x *StatsBucket) GetLocalPrefChanges() int32 {
	if x != nil {
		return x.LocalPrefChanges
	}
	return 0
}

type LastAttrs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Communities   string                 `protobuf:"bytes,2,opt,name=communities,proto3" json:"communities,omitempty"`
	NextHop       string                 `protobuf:"bytes,3,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Aggregator    string                 `protobuf:"bytes,4,opt,name=aggregator,proto3" json:"aggregator,omitempty"`
	LastPathLen   int32                  `protobuf:"varint,5,opt,name=last_path_len,json=lastPathLen,proto3" json:"last_path_len,omitempty"`
	OriginAsn     uint32                 `protobuf:"varint,6,opt,name=origin_asn,json=originAsn,proto3" json:"origin_asn,omitempty"`
	Med           int32                  `protobuf:"varint,7,opt,name=med,proto3" json:"med,omitempty"`
	LocalPref     int32                  `protobuf:"varint,8,opt,name=local_pref,json=localPref,proto3" json:"local_pref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastAttrs) Reset() {
	*x = LastAttrs{}
	mi := &file_v1_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastAttrs) ProtoMessage() {}

func (x *LastAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_v1_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastAttrs.ProtoReflect.Descriptor instead.
func (*LastAttrs) Descriptor() ([]byte, []int) {
	return file_v1_v1_proto_rawDescGZIP(), []int{1}
}

func (x *LastAttrs) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LastAttrs) GetCommunities() string {
	if x != nil {
		return x.Communities
	}
	return ""
}

func (x *LastAttrs) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *LastAttrs) GetAggregator() string {
	if x != nil {
		return x.Aggregator
	}
	return ""
}

func (x *LastAttrs) GetLastPathLen() int32 {
	if x != nil {
		return x.LastPathLen
	}
	return 0
}

func (x *LastAttrs) GetOriginAsn() uint32 {
	if x != nil {
		return x.OriginAsn
	}
	return 0
}

func (x *LastAttrs) GetMed() int32 {
	if x != nil {
		return x.Med
	}
	return 0
}

func (x *LastAttrs) GetLocalPref() int32 {
	if x != nil {
		return x.LocalPref
	}
	return 0
}

type PrefixState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Buckets              map[int64]*StatsBucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // timestamp (minute-aligned) -> bucket
	PeerLastAttrs        map[string]*LastAttrs  `protobuf:"bytes,2,rep,name=peer_last_attrs,json=peerLastAttrs,proto3" json:"peer_last_attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastUpdateTs         int64                  `protobuf:"varint,3,opt,name=last_update_ts,json=lastUpdateTs,proto3" json:"last_update_ts,omitempty"`
	StartTimeTs          int64                  `protobuf:"varint,4,opt,name=start_time_ts,json=startTimeTs,proto3" json:"start_time_ts,omitempty"`
	UncategorizedCounted bool                   `protobuf:"varint,5,opt,name=uncategorized_counted,json=uncategorizedCounted,proto3" json:"uncategorized_counted,omitempty"`
	ClassifiedType       int32                  `protobuf:"varint,6,opt,name=classified_type,json=classifiedType,proto3" json:"classified_type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PrefixState) Reset() {
	*x = PrefixState{}
	mi := &file_v1_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixState) ProtoMessage() {}

func (x *PrefixState) ProtoReflect() protoreflect.Message {
	mi := &file_v1_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixState.ProtoReflect.Descriptor instead.
func (*PrefixState) Descriptor() ([]byte, []int) {
	return file_v1_v1_proto_rawDescGZIP(), []int{2}
}

func (x *PrefixState) GetBuckets() map[int64]*StatsBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *PrefixState) GetPeerLastAttrs() map[string]*LastAttrs {
	if x != nil {
		return x.PeerLastAttrs
	}
	return nil
}

func (x *PrefixState) GetLastUpdateTs() int64 {
	if x != nil {
		return x.LastUpdateTs
	}
	return 0
}

func (x *PrefixState) GetStartTimeTs() int64 {
	if x != nil {
		return x.StartTimeTs
	}
	return 0
}

func (x *PrefixState) GetUncategorizedCounted() bool {
	if x != nil {
		return x.UncategorizedCounted
	}
	return false
}

func (x *PrefixState) GetClassifiedType() int32 {
	if x != nil {
		return x.ClassifiedType
	}
	return 0
}

var File_v1_v1_proto protoreflect.FileDescriptor

const file_v1_v1_proto_rawDesc = "" +
	"\n" +
	"\vv1/v1.proto\x12\x06bgp.v1\"\xdc\x03\n" +
	"\vStatsBucket\x12$\n" +
	"\rannouncements\x18\x01 \x01(\x05R\rannouncements\x12 \n" +
	"\vwithdrawals\x18\x02 \x01(\x05R\vwithdrawals\x12%\n" +
	"\x0etotal_messages\x18\x03 \x01(\x05R\rtotalMessages\x12!\n" +
	"\fpath_changes\x18\x04 \x01(\x05R\vpathChanges\x12+\n" +
	"\x11community_changes\x18\x05 \x01(\x05R\x10communityChanges\x12(\n" +
	"\x10next_hop_changes\x18\x06 \x01(\x05R\x0enextHopChanges\x12-\n" +
	"\x12aggregator_changes\x18\a \x01(\x05R\x11aggregatorChanges\x122\n" +
	"\x15path_length_increases\x18\b \x01(\x05R\x13pathLengthIncreases\x122\n" +
	"\x15path_length_decreases\x18\t \x01(\x05R\x13pathLengthDecreases\x12\x1f\n" +
	"\vmed_changes\x18\n" +
	" \x01(\x05R\n" +
	"medChanges\x12,\n" +
	"\x12local_pref_changes\x18\v \x01(\x05R\x10localPrefChanges\"\xf0\x01\n" +
	"\tLastAttrs\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12 \n" +
	"\vcommunities\x18\x02 \x01(\tR\vcommunities\x12\x19\n" +
	"\bnext_hop\x18\x03 \x01(\tR\anextHop\x12\x1e\n" +
	"\n" +
	"aggregator\x18\x04 \x01(\tR\n" +
	"aggregator\x12\"\n" +
	"\rlast_path_len\x18\x05 \x01(\x05R\vlastPathLen\x12\x1d\n" +
	"\n" +
	"origin_asn\x18\x06 \x01(\rR\toriginAsn\x12\x10\n" +
	"\x03med\x18\a \x01(\x05R\x03med\x12\x1d\n" +
	"\n" +
	"local_pref\x18\b \x01(\x05R\tlocalPref\"\xe7\x03\n" +
	"\vPrefixState\x12:\n" +
	"\abuckets\x18\x01 \x03(\v2 .bgp.v1.PrefixState.BucketsEntryR\abuckets\x12N\n" +
	"\x0fpeer_last_attrs\x18\x02 \x03(\v2&.bgp.v1.PrefixState.PeerLastAttrsEntryR\rpeerLastAttrs\x12$\n" +
	"\x0elast_update_ts\x18\x03 \x01(\x03R\flastUpdateTs\x12\"\n" +
	"\rstart_time_ts\x18\x04 \x01(\x03R\vstartTimeTs\x123\n" +
	"\x15uncategorized_counted\x18\x05 \x01(\bR\x14uncategorizedCounted\x12'\n" +
	"\x0fclassified_type\x18\x06 \x01(\x05R\x0eclassifiedType\x1aO\n" +
	"\fBucketsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.bgp.v1.StatsBucketR\x05value:\x028\x01\x1aS\n" +
	"\x12PeerLastAttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.bgp.v1.LastAttrsR\x05value:\x028\x01BBZ@github.com/sudorandom/bgp-stream/pkg/bgpengine/proto/v1;bgpprotob\x06proto3"

var (
	file_v1_v1_proto_rawDescOnce sync.Once
	file_v1_v1_proto_rawDescData []byte
)

func file_v1_v1_proto_rawDescGZIP() []byte {
	file_v1_v1_proto_rawDescOnce.Do(func() {
		file_v1_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_v1_proto_rawDesc), len(file_v1_v1_proto_rawDesc)))
	})
	return file_v1_v1_proto_rawDescData
}

var file_v1_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_v1_proto_goTypes = []any{
	(*StatsBucket)(nil), // 0: bgp.v1.StatsBucket
	(*LastAttrs)(nil),   // 1: bgp.v1.LastAttrs
	(*PrefixState)(nil), // 2: bgp.v1.PrefixState
	nil,                 // 3: bgp.v1.PrefixState.BucketsEntry
	nil,                 // 4: bgp.v1.PrefixState.PeerLastAttrsEntry
}
var file_v1_v1_proto_depIdxs = []int32{
	3, // 0: bgp.v1.PrefixState.buckets:type_name -> bgp.v1.PrefixState.BucketsEntry
	4, // 1: bgp.v1.PrefixState.peer_last_attrs:type_name -> bgp.v1.PrefixState.PeerLastAttrsEntry
	0, // 2: bgp.v1.PrefixState.BucketsEntry.value:type_name -> bgp.v1.StatsBucket
	1, // 3: bgp.v1.PrefixState.PeerLastAttrsEntry.value:type_name -> bgp.v1.LastAttrs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_v1_proto_init() }
func file_v1_v1_proto_init() {
	if File_v1_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_v1_proto_rawDesc), len(file_v1_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_v1_proto_goTypes,
		DependencyIndexes: file_v1_v1_proto_depIdxs,
		MessageInfos:      file_v1_v1_proto_msgTypes,
	}.Build()
	File_v1_v1_proto = out.File
	file_v1_v1_proto_goTypes = nil
	file_v1_v1_proto_depIdxs = nil
}
